name: Update README with Latest Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Latest Commit
        id: get_commit
        run: echo "::set-output name=commit::$(git log -1 --pretty=format:'%H - %s')"

      - name: Update README
        id: update_readme
        run: |
          sed -i "s|<!-- COMMIT-LIST:START -->|<!-- COMMIT-LIST:START -->\n${{ steps.get_commit.outputs.commit }}|" README.md

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README with latest commit
          branch: main
          file_pattern: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
