name: Update README with Latest Commits

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get List of Repositories
        id: get_repos
        run: |
          # Get list of repositories
          repos=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/user/repos?per_page=100")

          # Save raw JSON response to file for debugging
          echo "$repos" > repos.json

          # Extract repository SSH URLs
          repos_urls=$(echo "$repos" | jq -r '.[] | .ssh_url')

          # Save extracted SSH URLs to file for debugging
          echo "$repos_urls" > repos_urls.txt

      - name: Check Repositories
        run: |
          cat repos.json
          cat repos_urls.txt

      - name: Get Latest Commits
        id: get_commits
        run: |
          commit_list=""
          while IFS= read -r repo; do
            repo_name=$(basename -s .git "$repo")
            git clone "$repo" temp-repo
            cd temp-repo
            latest_commit=$(git log -1 --pretty=format:'%H')
            commit_message=$(git log -1 --pretty=format:"%h - %s" $latest_commit)
            commit_url="https://github.com/${{ github.repository_owner }}/$repo_name/commit/$latest_commit"
            commit_list="${commit_list}\n* [${commit_message}](${commit_url})"
            cd ..
            rm -rf temp-repo
          done < repos_urls.txt

          echo "COMMIT_LIST=${commit_list}" >> $GITHUB_ENV

      - name: Update README
        id: update_readme
        run: |
          sed -i "s|<!-- COMMIT-LIST:START -->|<!-- COMMIT-LIST:START -->\n${{ env.COMMIT_LIST }}|" README.md

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          message: 'Update README with latest commits'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
