name: Update README with Latest Commit

on:
  push:                #@todo solve error
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Commit
        id: get_commit
        run: |
          echo "commit=$(git log -1 --pretty=format:'%H - %s')" >> $GITHUB_ENV

      - name: Update README
        id: update_readme
        run: |
          sed -i "s|<!-- COMMIT-LIST:START -->|<!-- COMMIT-LIST:START -->\n${{ env.commit }}|" README.md

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          message: 'Update README with latest commit'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
