name: Update README with Latest Commits

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' 
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Commits
        id: get_commits
        run: |
          # Fetch all repositories
          repos=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/user/repos?per_page=100" | \
            jq -r '.[].ssh_url')
          
          # Collect latest commits for each repository
          commit_list=""
          for repo in $repos; do
            repo_name=$(basename -s .git $repo)
            latest_commit=$(git ls-remote $repo HEAD | awk '{print $1}')
            commit_message=$(git log -1 --pretty=format:"%h - %s" $latest_commit)
            commit_url="https://github.com/${{ github.repository_owner }}/$repo_name/commit/$latest_commit"
            commit_list="${commit_list}\n* [${commit_message}](${commit_url})"
          done

          echo "COMMIT_LIST=${commit_list}" >> $GITHUB_ENV

      - name: Update README
        id: update_readme
        run: |
          sed -i "s|<!-- COMMIT-LIST:START -->|<!-- COMMIT-LIST:START -->\n${{ env.COMMIT_LIST }}|" README.md

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          message: 'Update README with latest commits'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
